name: Full Compile Check

on: [workflow_dispatch]

jobs:
  build-wasm:
    name: WebAssembly/Emscripten
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
        with: {submodules: 'recursive'}
      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: '3.1.69'
          actions-cache-folder: 'emsdk-cache'
      - name: Verify emcc
        run: emcc --version
      - run: python3 build.py --emscripten --dependencies --configure --build
